version: '3.7'

services:
  haandbib:
    container_name: haandbib
    hostname: haandbib
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: mysql://root:haandbib@mysql:3306/haandbib
      PORT: 3001
      NODE_ENV: development
      AUTH_SESSION_TTL: 3600
      AUTH_SECRET: secret
      DEFAULT_PASSWORD: any_pass
      JWT_SALT: 12
    depends_on:
      - mysql
      - redis
    networks:
      - app-network
      - external-network

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306/tcp'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'dbsql:3306']
      timeout: 20s
      retries: 10
    environment:
      MYSQL_DATABASE: haandbib
      MYSQL_ROOT_PASSWORD: haandbib
    volumes:
      - ./dbsql/dbmysql/mysql:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine3.13
    container_name: redis
    command: redis-server
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '6379:6379'
    networks:
      - app-network
      - redis-network

networks:
  app-network:
    driver: bridge
  redis-network:
    driver: bridge
  external-network:
    external: true

volumes:
  dbdata:
