import { ExampleObject, ReferenceObject } from 'openapi-comment-parser';

export default {
  GetLoanSimulationWithConsultantCommissionResponse: {
    value: {
      salary: 1500,
      maxInstallmentValueBySalary: 525,
      consultantCommission: 10,
      firstPaymentDates: [
        '2022-04-30T03:00:00.000Z',
        '2022-05-30T03:00:00.000Z',
        '2022-06-15T03:00:00.000Z',
      ],
      consultantCommissionValue: 100,
      isRequestedValueValid: true,
      feesValue: 141.06,
      cardFees: 96,
      bankProcessingFees: 80,
      totalValue: 2109.0600000000004,
      telemedicineFees: 192,
      installments: [
        {
          reference: 'abril/2022',
          cardFees: 12,
          telemedicineFees: 24,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 10,
          consultantCommissionValue: 12.5,
          fees: 4.62,
          feesValue: 8.66,
          finalValue: 254.66,
        },
        {
          reference: 'maio/2022',
          cardFees: 12,
          telemedicineFees: 24,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 10,
          consultantCommissionValue: 12.5,
          fees: 10.23,
          feesValue: 19.18,
          finalValue: 265.18,
        },
        {
          reference: 'junho/2022',
          cardFees: 12,
          telemedicineFees: 24,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 10,
          consultantCommissionValue: 12.5,
          fees: 9.9,
          feesValue: 18.56,
          finalValue: 264.56,
        },
        {
          reference: 'julho/2022',
          cardFees: 12,
          telemedicineFees: 24,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 10,
          consultantCommissionValue: 12.5,
          fees: 10.23,
          feesValue: 19.18,
          finalValue: 265.18,
        },
        {
          reference: 'agosto/2022',
          cardFees: 12,
          telemedicineFees: 24,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 10,
          consultantCommissionValue: 12.5,
          fees: 10.23,
          feesValue: 19.18,
          finalValue: 265.18,
        },
        {
          reference: 'setembro/2022',
          cardFees: 12,
          telemedicineFees: 24,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 10,
          consultantCommissionValue: 12.5,
          fees: 9.9,
          feesValue: 18.56,
          finalValue: 264.56,
        },
        {
          reference: 'outubro/2022',
          cardFees: 12,
          telemedicineFees: 24,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 10,
          consultantCommissionValue: 12.5,
          fees: 10.23,
          feesValue: 19.18,
          finalValue: 265.18,
        },
        {
          reference: 'novembro/2022',
          cardFees: 12,
          telemedicineFees: 24,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 10,
          consultantCommissionValue: 12.5,
          fees: 9.9,
          feesValue: 18.56,
          finalValue: 264.56,
        },
      ],
    },
  },
  GetLoanSimulationWithoutTelemedicineResponse: {
    value: {
      salary: 1500,
      maxInstallmentValueBySalary: 525,
      consultantCommission: 0,
      firstPaymentDates: [
        '2022-04-30T03:00:00.000Z',
        '2022-05-30T03:00:00.000Z',
        '2022-06-14T03:00:00.000Z',
      ],
      consultantCommissionValue: 0,
      isRequestedValueValid: true,
      feesValue: 141.68,
      cardFees: 96,
      bankProcessingFees: 80,
      totalValue: 1817.68,
      telemedicineFees: 0,
      installments: [
        {
          reference: 'abril/2022',
          cardFees: 12,
          telemedicineFees: 0,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 0,
          consultantCommissionValue: 0,
          fees: 4.95,
          feesValue: 9.28,
          finalValue: 218.78,
        },
        {
          reference: 'maio/2022',
          cardFees: 12,
          telemedicineFees: 0,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 0,
          consultantCommissionValue: 0,
          fees: 10.23,
          feesValue: 19.18,
          finalValue: 228.68,
        },
        {
          reference: 'junho/2022',
          cardFees: 12,
          telemedicineFees: 0,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 0,
          consultantCommissionValue: 0,
          fees: 9.9,
          feesValue: 18.56,
          finalValue: 228.06,
        },
        {
          reference: 'julho/2022',
          cardFees: 12,
          telemedicineFees: 0,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 0,
          consultantCommissionValue: 0,
          fees: 10.23,
          feesValue: 19.18,
          finalValue: 228.68,
        },
        {
          reference: 'agosto/2022',
          cardFees: 12,
          telemedicineFees: 0,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 0,
          consultantCommissionValue: 0,
          fees: 10.23,
          feesValue: 19.18,
          finalValue: 228.68,
        },
        {
          reference: 'setembro/2022',
          cardFees: 12,
          telemedicineFees: 0,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 0,
          consultantCommissionValue: 0,
          fees: 9.9,
          feesValue: 18.56,
          finalValue: 228.06,
        },
        {
          reference: 'outubro/2022',
          cardFees: 12,
          telemedicineFees: 0,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 0,
          consultantCommissionValue: 0,
          fees: 10.23,
          feesValue: 19.18,
          finalValue: 228.68,
        },
        {
          reference: 'novembro/2022',
          cardFees: 12,
          telemedicineFees: 0,
          bankProcessingFees: 10,
          installmentFactor: 187.5,
          consultantCommission: 0,
          consultantCommissionValue: 0,
          fees: 9.9,
          feesValue: 18.56,
          finalValue: 228.06,
        },
      ],
    },
  },
  GetLoanSimulationWithoutConsultantCommissionResponse: {
    value: {
      statusCode: 200,
      statusCodeAsString: 'OK',
      data: {
        salary: 1500,
        maxInstallmentValueBySalary: 525,
        consultantCommission: 0,
        firstPaymentDates: [
          '2022-04-30T03:00:00.000Z',
          '2022-05-30T03:00:00.000Z',
          '2022-06-12T03:00:00.000Z',
        ],
        consultantCommissionValue: 0,
        isRequestedValueValid: true,
        feesValue: 142.92000000000002,
        cardFees: 96,
        bankProcessingFees: 80,
        totalValue: 2010.92,
        telemedicineFees: 192,
        installments: [
          {
            reference: 'abril/2022',
            cardFees: 12,
            telemedicineFees: 24,
            bankProcessingFees: 10,
            installmentFactor: 187.5,
            consultantCommission: 0,
            consultantCommissionValue: 0,
            fees: 5.61,
            feesValue: 10.52,
            finalValue: 244.02,
          },
          {
            reference: 'maio/2022',
            cardFees: 12,
            telemedicineFees: 24,
            bankProcessingFees: 10,
            installmentFactor: 187.5,
            consultantCommission: 0,
            consultantCommissionValue: 0,
            fees: 10.23,
            feesValue: 19.18,
            finalValue: 252.68,
          },
          {
            reference: 'junho/2022',
            cardFees: 12,
            telemedicineFees: 24,
            bankProcessingFees: 10,
            installmentFactor: 187.5,
            consultantCommission: 0,
            consultantCommissionValue: 0,
            fees: 9.9,
            feesValue: 18.56,
            finalValue: 252.06,
          },
          {
            reference: 'julho/2022',
            cardFees: 12,
            telemedicineFees: 24,
            bankProcessingFees: 10,
            installmentFactor: 187.5,
            consultantCommission: 0,
            consultantCommissionValue: 0,
            fees: 10.23,
            feesValue: 19.18,
            finalValue: 252.68,
          },
          {
            reference: 'agosto/2022',
            cardFees: 12,
            telemedicineFees: 24,
            bankProcessingFees: 10,
            installmentFactor: 187.5,
            consultantCommission: 0,
            consultantCommissionValue: 0,
            fees: 10.23,
            feesValue: 19.18,
            finalValue: 252.68,
          },
          {
            reference: 'setembro/2022',
            cardFees: 12,
            telemedicineFees: 24,
            bankProcessingFees: 10,
            installmentFactor: 187.5,
            consultantCommission: 0,
            consultantCommissionValue: 0,
            fees: 9.9,
            feesValue: 18.56,
            finalValue: 252.06,
          },
          {
            reference: 'outubro/2022',
            cardFees: 12,
            telemedicineFees: 24,
            bankProcessingFees: 10,
            installmentFactor: 187.5,
            consultantCommission: 0,
            consultantCommissionValue: 0,
            fees: 10.23,
            feesValue: 19.18,
            finalValue: 252.68,
          },
          {
            reference: 'novembro/2022',
            cardFees: 12,
            telemedicineFees: 24,
            bankProcessingFees: 10,
            installmentFactor: 187.5,
            consultantCommission: 0,
            consultantCommissionValue: 0,
            fees: 9.9,
            feesValue: 18.56,
            finalValue: 252.06,
          },
        ],
      },
    },
  },
  GetLoanSimulationBasedOnRequestedValuePayloadComplete: {
    value: {
      salary: 1500,
      salaryReceiptDate:
        'Sat Apr 30 2022 00:00:00 GMT-0300 (Horário Padrão de Brasília)',
      requestedValue: 1000,
      numberOfInstallments: 8,
      joinedTelemedicine: true,
      consultantId: 1,
    },
  },
  GetLoanSimulationBasedOnRequestedValuePayloadWithoutsalaryReceiptDate: {
    value: {
      salary: 1500,
      requestedValue: 1000,
      numberOfInstallments: 8,
      joinedTelemedicine: true,
      consultantId: 1,
    },
  },
  GetLoanSimulationBasedOnRequestedValuePayloadWithoutConsultantCommission: {
    value: {
      salary: 1500,
      salaryReceiptDate:
        'Sat Apr 30 2022 00:00:00 GMT-0300 (Horário Padrão de Brasília)',
      requestedValue: 1000,
      numberOfInstallments: 8,
      joinedTelemedicine: true,
    },
  },
  GetLoanSimulationBadRequest: {
    value: {
      code: 'GENERIC_ERROR',
      statusCode: 400,
      statusCodeAsString: 'BAD_REQUEST',
      description: 'Missing or invalid param',
      validationErrors: [
        {
          fieldName: 'numberOfInstallments',
          friendlyFieldName: 'numberOfInstallments',
          message: '"numberOfInstallments" is required',
        },
        {
          fieldName: 'requestedValue',
          friendlyFieldName: 'requestedValue',
          message: '"requestedValue" is required',
        },
        {
          fieldName: 'salary',
          friendlyFieldName: 'salary',
          message: '"salary" is required',
        },
      ],
    },
  },
  CreateConsultantResponse: {
    value: {
      name: 'String',
      taxId: 1020312465,
      city: 'São Luis',
      state: 'Maranhão',
      commission: 10,
      createdBy: 'admin',
      updatedBy: 'admin',
      createdAt: '10-10-2020',
      updatedAt: '20-03-2021',
      deletedAt: '03-09-2022',
    },
  },
  ConsultantResponse: {
    value: {
      name: 'String',
      taxId: 1020312465,
      city: 'São Luis',
      state: 'Maranhão',
      commission: 10,
      createdBy: 'admin',
      updatedBy: 'admin',
      createdAt: '10-10-2020',
      updatedAt: '20-03-2021',
      deletedAt: '03-09-2022',
    },
  },
} as { [key: string]: ExampleObject | ReferenceObject };
