import { ExampleObject, ReferenceObject } from 'openapi-comment-parser';

export default {
  GetAddressesByAssociatedIdResponse: {
    value: {
      statusCode: 200,
      statusCodeAsString: 'OK',
      data: [
        {
          id: 1,
          isDefault: true,
          addressType: 'HOUSE',
          postalCode: '78595-970',
          street: 'Avenida Governador Dante Martins de Oliveira 115',
          houseNumber: '123',
          complement: '',
          district: 'Centro',
          city: 'Apiacás',
          state: 'Mato Grosso',
          associatedId: 1,
        },
      ],
    },
  },
  GetBankAccountsByAssociatedIdResponse: {
    value: {
      statusCode: 200,
      statusCodeAsString: 'OK',
      data: [
        {
          id: 1,
          bank: 'Itaú',
          agency: '000',
          accountType: 'Corrente',
          accountNumber: '23132',
          pixKey: 'eloa_freitas@superigi.com.br',
          pixType: null,
          isDefault: true,
          associatedId: 1,
        },
      ],
    },
  },
  GetEmploymentRelationshipsByAssociatedIdResponse: {
    value: {
      statusCode: 200,
      statusCodeAsString: 'OK',
      data: [
        {
          id: 1,
          isDefault: true,
          occupation: 'Arquiteta',
          salary: '4312.20',
          paymentDay: 5,
          registerNumber: '2108602049',
          contractType: 'HIRED',
          finalDate: null,
          publicAgency: 'MiSupremo Tribunal Federal',
          associatedId: 1,
        },
      ],
    },
  },
  CreateAssociatedResponse: {
    value: {
      statusCode: 201,
      statusCodeAsString: 'CREATED',
      data: {
        id: 11,
        name: 'teste',
        lastName: 'teste',
        affiliation: 'ASES Vitória',
        gender: 'MALE',
        birthDate: '1995-04-25T00:00:00.000Z',
        maritalStatus: 'SINGLE',
        nationality: 'BRAZILIAN',
        placeOfBirth: 'São Paulo - SP',
        taxId: '440.630.768-06',
        registerId: '48976343',
        emissionState: 'São Paulo',
        issuingAgency: 'SSP - Secretaria de Segurança Pública',
        emissionDate: '2020-10-20T00:00:00.000Z',
        cellPhone: '(12)3 1564-6546',
        email: 'teste@mail.com',
        father: 'pa',
        mother: 'mãe',
        partner: 'conjuge',
        createdBy: 'afonsobr',
        updatedBy: null,
        createdAt: '2022-08-18T00:12:26.000Z',
        updatedAt: '2022-08-18T00:12:25.518Z',
        deletedAt: null,
        addresses: [
          {
            id: 11,
            addressType: 'HOUSE',
            postalCode: '04184-000',
            street: 'Rua Professor Arnaldo João Semeraro',
            houseNumber: '621',
            complement: '',
            district: 'Jardim Santa Emília',
            city: 'São Paulo',
            state: 'São Paulo',
            associatedId: 11,
          },
        ],
        employmentRelationships: [
          {
            id: 11,
            occupation: 'Zootecnista',
            salary: '2,00',
            paymentDay: 1,
            registerNumber: '1',
            contractType: 'INTERN',
            finalDate: '2020-10-20T00:00:00.000Z',
            publicAgency: 'INSS',
            associatedId: 11,
          },
        ],
        bankAccounts: [
          {
            id: 11,
            bank: '260 - NU PAGAMENTOS - IP',
            agency: '001',
            accountType: 'checkingAccount',
            accountNumber: '1',
            pixKey: '132165465',
            pixType: 'CPF ou CNPJ',
            associatedId: 11,
          },
        ],
      },
    },
  },
  CreateAssociatedBadRequestResponse: {
    value: {
      code: 'GENERIC_ERROR',
      statusCode: 400,
      statusCodeAsString: 'BAD_REQUEST',
      description: 'Missing or invalid param',
      validationErrors: [
        {
          fieldName: 'name',
          friendlyFieldName: 'nome',
          message: '"nome" is required',
        },
        {
          fieldName: 'lastName',
          friendlyFieldName: 'sobrenome',
          message: '"sobrenome" is required',
        },
        {
          fieldName: 'affiliation',
          friendlyFieldName: 'afiliação',
          message: '"afiliação" is required',
        },
        {
          fieldName: 'gender',
          friendlyFieldName: 'sexo',
          message: '"sexo" is required',
        },
        {
          fieldName: 'birthDate',
          friendlyFieldName: 'birthDate',
          message: '"birthDate" is required',
        },
        {
          fieldName: 'maritalStatus',
          friendlyFieldName: 'estado-civil',
          message: '"estado-civil" is required',
        },
        {
          fieldName: 'nationality',
          friendlyFieldName: 'nacionalidade',
          message: '"nacionalidade" is required',
        },
        {
          fieldName: 'placeOfBirth',
          friendlyFieldName: 'naturalidade',
          message: '"naturalidade" is required',
        },
        {
          fieldName: 'taxId',
          friendlyFieldName: 'cpf',
          message: '"cpf" is required',
        },
        {
          fieldName: 'registerId',
          friendlyFieldName: 'rg',
          message: '"rg" is required',
        },
        {
          fieldName: 'emissionState',
          friendlyFieldName: 'estado-emissor',
          message: '"estado-emissor" is required',
        },
        {
          fieldName: 'issuingAgency',
          friendlyFieldName: 'orgao-emissor',
          message: '"orgao-emissor" is required',
        },
        {
          fieldName: 'emissionDate',
          friendlyFieldName: 'data-emissao',
          message: '"data-emissao" is required',
        },
        {
          fieldName: 'cellPhone',
          friendlyFieldName: 'celular',
          message: '"celular" is required',
        },
        {
          fieldName: 'email',
          friendlyFieldName: 'email',
          message: '"email" is required',
        },
        {
          fieldName: 'father',
          friendlyFieldName: 'pai',
          message: '"pai" is required',
        },
        {
          fieldName: 'mother',
          friendlyFieldName: 'mãe',
          message: '"mãe" is required',
        },
        {
          fieldName: 'addresses',
          friendlyFieldName: 'addresses',
          message: '"addresses" is required',
        },
        {
          fieldName: 'employmentRelationships',
          friendlyFieldName: 'employmentRelationships',
          message: '"employmentRelationships" is required',
        },
      ],
    },
  },
  GetAllAssociatedsResponse: {
    value: {
      statusCode: 200,
      statusCodeAsString: 'OK',
      data: {
        totalResults: 1,
        totalPages: 1,
        currentPage: 1,
        data: [
          {
            id: 1,
            name: 'Márcio',
            lastName: 'Das Neves',
            gender: 'Masculino',
            birthDate: '1991-06-06T00:00:00.000Z',
            maritalStatus: 'Casado',
            nationality: 'Brasileiro',
            placeOfBirth: 'Poti',
            taxId: '884.747.923-12',
            registerId: '21.860.204-2',
            emissionState: 'Ceará',
            issuingAgency: 'Secretaria de Segurança Pública',
            emissionDate: '2022-10-10T00:00:00.000Z',
            cellPhone: '(88) 3768-4973',
            email: 'marcio.davi.dasneves@likaleal.com.br',
            father: 'Vicente Alexandre das Neves',
            mother: 'Allana Rafaela',
            partner: 'Joana Maria das Neves',
            createdBy: 'João',
            updatedBy: null,
            createdAt: '2022-10-05T02:01:33.000Z',
            updatedAt: '2022-10-12T21:43:09.146Z',
            deletedAt: null,
            addresses: [
              {
                id: 1,
                isDefault: true,
                addressType: 'HOUSE',
                postalCode: '78595-970',
                street: 'Avenida Governador Dante Martins de Oliveira 115',
                houseNumber: '123',
                complement: '',
                district: 'Centro',
                city: 'Apiacás',
                state: 'Mato Grosso',
                associatedId: 1,
              },
            ],
            employmentRelationships: [
              {
                id: 1,
                isDefault: true,
                occupation: 'Arquiteta',
                salary: '4312.20',
                paymentDay: 5,
                registerNumber: '2108602049',
                contractType: 'HIRED',
                finalDate: null,
                publicAgency: 'MiSupremo Tribunal Federal',
                associatedId: 1,
              },
            ],
            bankAccounts: [
              {
                id: 1,
                bank: 'Itaú',
                agency: '000',
                accountType: 'Corrente',
                accountNumber: '23132',
                pixKey: 'eloa_freitas@superigi.com.br',
                pixType: null,
                isDefault: true,
                associatedId: 1,
              },
            ],
            benefits: [
              {
                id: 1,
                associatedId: 1,
                commission: 0,
                administrationFeeValue: 1000,
                hasGratification: true,
                joinedTelemedicine: true,
                bank: 'Itaú',
                publicAgency: 'MiSupremo Tribunal Federal',
                contractModel: '',
                installmentNumber: 8,
                initialDate: '2022-11-05T00:00:00.000Z',
                financialAssistanceValue: 3648,
                installmentValue: 456,
                name: 'Márcio',
                lastName: 'Das Neves',
                gender: 'Masculino',
                birthDate: '1991-06-06T00:00:00.000Z',
                maritalStatus: 'Casado',
                nationality: 'Brasileiro',
                placeOfBirth: 'Poti',
                taxId: '884.747.923-12',
                registerId: '21.860.204-2',
                emissionState: 'Ceará',
                issuingAgency: 'Secretaria de Segurança Pública',
                emissionDate: '2022-10-10T00:00:00.000Z',
                cellPhone: '(88) 3768-4973',
                email: 'marcio.davi.dasneves@likaleal.com.br',
                father: 'Vicente Alexandre das Neves',
                mother: 'Allana Rafaela',
                partner: 'Joana Maria das Neves',
                occupation: 'Arquiteta',
                salary: '4312.20',
                paymentDay: 5,
                registerNumber: '2108602049',
                contractType: 'N',
                finalDate: null,
                agency: '000',
                accountType: 'Corrente',
                accountNumber: '23132',
                pixKey: 'eloa_freitas@superigi.com.br',
                pixType: null,
                addressType: 'HOUSE',
                postalCode: '78595-970',
                street: 'Avenida Governador Dante Martins de Oliveira 115',
                houseNumber: '123',
                complement: '',
                district: 'Centro',
                city: 'Apiacás',
                state: 'Mato Grosso',
                consultantId: null,
                type: 'N',
                status: 'UNDER_ANALYSIS',
                affiliationId: 1,
                createdBy: 'João',
                updatedBy: null,
                createdAt: '2022-10-05T02:01:33.000Z',
                updatedAt: '2022-10-11T00:25:28.889Z',
                deletedAt: null,
                affiliation: {
                  id: 1,
                  name: 'ASES Vitória',
                  createdAt: '2022-10-05T02:01:32.000Z',
                  updatedAt: '2022-10-12T21:43:08.570Z',
                  deletedAt: null,
                },
                consultant: null,
              },
              {
                id: 2,
                associatedId: 1,
                commission: 0,
                administrationFeeValue: 1000,
                hasGratification: true,
                joinedTelemedicine: true,
                bank: 'Itaú',
                publicAgency: 'MiSupremo Tribunal Federal',
                contractModel: '',
                installmentNumber: 8,
                initialDate: '2022-11-05T00:00:00.000Z',
                financialAssistanceValue: 3648,
                installmentValue: 456,
                name: 'Márcio',
                lastName: 'Das Neves',
                gender: 'Masculino',
                birthDate: '1991-06-06T00:00:00.000Z',
                maritalStatus: 'Casado',
                nationality: 'Brasileiro',
                placeOfBirth: 'Poti',
                taxId: '884.747.923-12',
                registerId: '21.860.204-2',
                emissionState: 'Ceará',
                issuingAgency: 'Secretaria de Segurança Pública',
                emissionDate: '2022-10-10T00:00:00.000Z',
                cellPhone: '(88) 3768-4973',
                email: 'marcio.davi.dasneves@likaleal.com.br',
                father: 'Vicente Alexandre das Neves',
                mother: 'Allana Rafaela',
                partner: 'Joana Maria das Neves',
                occupation: 'Arquiteta',
                salary: '4312.20',
                paymentDay: 5,
                registerNumber: '2108602049',
                contractType: 'N',
                finalDate: null,
                agency: '000',
                accountType: 'Corrente',
                accountNumber: '23132',
                pixKey: 'eloa_freitas@superigi.com.br',
                pixType: null,
                addressType: 'HOUSE',
                postalCode: '78595-970',
                street: 'Avenida Governador Dante Martins de Oliveira 115',
                houseNumber: '123',
                complement: '',
                district: 'Centro',
                city: 'Apiacás',
                state: 'Mato Grosso',
                consultantId: null,
                type: 'N',
                status: 'UNDER_ANALYSIS',
                affiliationId: 1,
                createdBy: 'afonsobr',
                updatedBy: null,
                createdAt: '2022-10-05T02:01:33.000Z',
                updatedAt: '2022-10-11T00:40:08.829Z',
                deletedAt: null,
                affiliation: {
                  id: 1,
                  name: 'ASES Vitória',
                  createdAt: '2022-10-05T02:01:32.000Z',
                  updatedAt: '2022-10-12T21:43:08.570Z',
                  deletedAt: null,
                },
                consultant: null,
              },
              {
                id: 3,
                associatedId: 1,
                commission: 0,
                administrationFeeValue: 1000,
                hasGratification: true,
                joinedTelemedicine: true,
                bank: 'Itaú',
                publicAgency: 'MiSupremo Tribunal Federal',
                contractModel: '',
                installmentNumber: 8,
                initialDate: '2022-11-05T00:00:00.000Z',
                financialAssistanceValue: 3648,
                installmentValue: 456,
                name: 'Márcio',
                lastName: 'Das Neves',
                gender: 'Masculino',
                birthDate: '1991-06-06T00:00:00.000Z',
                maritalStatus: 'Casado',
                nationality: 'Brasileiro',
                placeOfBirth: 'Poti',
                taxId: '884.747.923-12',
                registerId: '21.860.204-2',
                emissionState: 'Ceará',
                issuingAgency: 'Secretaria de Segurança Pública',
                emissionDate: '2022-10-10T00:00:00.000Z',
                cellPhone: '(88) 3768-4973',
                email: 'marcio.davi.dasneves@likaleal.com.br',
                father: 'Vicente Alexandre das Neves',
                mother: 'Allana Rafaela',
                partner: 'Joana Maria das Neves',
                occupation: 'Arquiteta',
                salary: '4312.20',
                paymentDay: 5,
                registerNumber: '2108602049',
                contractType: 'N',
                finalDate: null,
                agency: '000',
                accountType: 'Corrente',
                accountNumber: '23132',
                pixKey: 'eloa_freitas@superigi.com.br',
                pixType: null,
                addressType: 'HOUSE',
                postalCode: '78595-970',
                street: 'Avenida Governador Dante Martins de Oliveira 115',
                houseNumber: '123',
                complement: '',
                district: 'Centro',
                city: 'Apiacás',
                state: 'Mato Grosso',
                consultantId: null,
                type: 'N',
                status: 'UNDER_ANALYSIS',
                affiliationId: 1,
                createdBy: 'afonsobr',
                updatedBy: null,
                createdAt: '2022-10-05T02:01:33.000Z',
                updatedAt: '2022-10-11T00:42:21.210Z',
                deletedAt: null,
                affiliation: {
                  id: 1,
                  name: 'ASES Vitória',
                  createdAt: '2022-10-05T02:01:32.000Z',
                  updatedAt: '2022-10-12T21:43:08.570Z',
                  deletedAt: null,
                },
                consultant: null,
              },
              {
                id: 4,
                associatedId: 1,
                commission: 0,
                administrationFeeValue: 1000,
                hasGratification: true,
                joinedTelemedicine: true,
                bank: 'Itaú',
                publicAgency: 'MiSupremo Tribunal Federal',
                contractModel: '',
                installmentNumber: 8,
                initialDate: '2022-11-05T00:00:00.000Z',
                financialAssistanceValue: 2898,
                installmentValue: 362.25,
                name: 'Márcio',
                lastName: 'Das Neves',
                gender: 'Masculino',
                birthDate: '1991-06-06T00:00:00.000Z',
                maritalStatus: 'Casado',
                nationality: 'Brasileiro',
                placeOfBirth: 'Poti',
                taxId: '884.747.923-12',
                registerId: '21.860.204-2',
                emissionState: 'Ceará',
                issuingAgency: 'Secretaria de Segurança Pública',
                emissionDate: '2022-10-10T00:00:00.000Z',
                cellPhone: '(88) 3768-4973',
                email: 'marcio.davi.dasneves@likaleal.com.br',
                father: 'Vicente Alexandre das Neves',
                mother: 'Allana Rafaela',
                partner: 'Joana Maria das Neves',
                occupation: 'Arquiteta',
                salary: '4312.20',
                paymentDay: 5,
                registerNumber: '2108602049',
                contractType: 'N',
                finalDate: null,
                agency: '000',
                accountType: 'Corrente',
                accountNumber: '23132',
                pixKey: 'eloa_freitas@superigi.com.br',
                pixType: null,
                addressType: 'HOUSE',
                postalCode: '78595-970',
                street: 'Avenida Governador Dante Martins de Oliveira 115',
                houseNumber: '123',
                complement: '',
                district: 'Centro',
                city: 'Apiacás',
                state: 'Mato Grosso',
                consultantId: null,
                type: 'N',
                status: 'UNDER_ANALYSIS',
                affiliationId: 1,
                createdBy: 'afonsobr',
                updatedBy: null,
                createdAt: '2022-10-05T02:01:33.000Z',
                updatedAt: '2022-10-11T00:47:21.855Z',
                deletedAt: null,
                affiliation: {
                  id: 1,
                  name: 'ASES Vitória',
                  createdAt: '2022-10-05T02:01:32.000Z',
                  updatedAt: '2022-10-12T21:43:08.570Z',
                  deletedAt: null,
                },
                consultant: null,
              },
            ],
            affiliations: [
              {
                id: 1,
                name: 'ASES Vitória',
                createdAt: '2022-10-05T02:01:32.000Z',
                updatedAt: '2022-10-12T21:43:08.570Z',
                deletedAt: null,
              },
            ],
          },
        ],
      },
    },
  },
  GetAssociatedByIdResponse: {
    value: {
      statusCode: 200,
      statusCodeAsString: 'OK',
      data: {
        id: 1,
        name: 'Márcio',
        lastName: 'Das Neves',
        gender: 'Masculino',
        birthDate: '1991-06-06T00:00:00.000Z',
        maritalStatus: 'Casado',
        nationality: 'Brasileiro',
        placeOfBirth: 'Poti',
        taxId: '884.747.923-12',
        registerId: '21.860.204-2',
        emissionState: 'Ceará',
        issuingAgency: 'Secretaria de Segurança Pública',
        emissionDate: '2022-10-10T00:00:00.000Z',
        cellPhone: '(88) 3768-4973',
        email: 'marcio.davi.dasneves@likaleal.com.br',
        father: 'Vicente Alexandre das Neves',
        mother: 'Allana Rafaela',
        partner: 'Joana Maria das Neves',
        createdBy: 'João',
        updatedBy: null,
        createdAt: '2022-10-05T02:01:33.000Z',
        updatedAt: '2022-10-12T21:58:05.460Z',
        deletedAt: null,
        addresses: [
          {
            id: 1,
            isDefault: true,
            addressType: 'HOUSE',
            postalCode: '78595-970',
            street: 'Avenida Governador Dante Martins de Oliveira 115',
            houseNumber: '123',
            complement: '',
            district: 'Centro',
            city: 'Apiacás',
            state: 'Mato Grosso',
            associatedId: 1,
          },
        ],
        employmentRelationships: [
          {
            id: 1,
            isDefault: true,
            occupation: 'Arquiteta',
            salary: '4312.20',
            paymentDay: 5,
            registerNumber: '2108602049',
            contractType: 'HIRED',
            finalDate: null,
            publicAgency: 'MiSupremo Tribunal Federal',
            associatedId: 1,
          },
        ],
        bankAccounts: [
          {
            id: 1,
            bank: 'Itaú',
            agency: '000',
            accountType: 'Corrente',
            accountNumber: '23132',
            pixKey: 'eloa_freitas@superigi.com.br',
            pixType: null,
            isDefault: true,
            associatedId: 1,
          },
        ],
        benefits: [
          {
            id: 1,
            associatedId: 1,
            commission: 0,
            administrationFeeValue: 1000,
            hasGratification: true,
            joinedTelemedicine: true,
            bank: 'Itaú',
            publicAgency: 'MiSupremo Tribunal Federal',
            contractModel: '',
            installmentNumber: 8,
            initialDate: '2022-11-05T00:00:00.000Z',
            financialAssistanceValue: 3648,
            installmentValue: 456,
            name: 'Márcio',
            lastName: 'Das Neves',
            gender: 'Masculino',
            birthDate: '1991-06-06T00:00:00.000Z',
            maritalStatus: 'Casado',
            nationality: 'Brasileiro',
            placeOfBirth: 'Poti',
            taxId: '884.747.923-12',
            registerId: '21.860.204-2',
            emissionState: 'Ceará',
            issuingAgency: 'Secretaria de Segurança Pública',
            emissionDate: '2022-10-10T00:00:00.000Z',
            cellPhone: '(88) 3768-4973',
            email: 'marcio.davi.dasneves@likaleal.com.br',
            father: 'Vicente Alexandre das Neves',
            mother: 'Allana Rafaela',
            partner: 'Joana Maria das Neves',
            occupation: 'Arquiteta',
            salary: '4312.20',
            paymentDay: 5,
            registerNumber: '2108602049',
            contractType: 'N',
            finalDate: null,
            agency: '000',
            accountType: 'Corrente',
            accountNumber: '23132',
            pixKey: 'eloa_freitas@superigi.com.br',
            pixType: null,
            addressType: 'HOUSE',
            postalCode: '78595-970',
            street: 'Avenida Governador Dante Martins de Oliveira 115',
            houseNumber: '123',
            complement: '',
            district: 'Centro',
            city: 'Apiacás',
            state: 'Mato Grosso',
            consultantId: null,
            type: 'N',
            status: 'UNDER_ANALYSIS',
            affiliationId: 1,
            createdBy: 'João',
            updatedBy: null,
            createdAt: '2022-10-05T02:01:33.000Z',
            updatedAt: '2022-10-11T00:25:28.889Z',
            deletedAt: null,
            affiliation: {
              id: 1,
              name: 'ASES Vitória',
              createdAt: '2022-10-05T02:01:32.000Z',
              updatedAt: '2022-10-12T21:58:04.970Z',
              deletedAt: null,
            },
            consultant: null,
          },
          {
            id: 2,
            associatedId: 1,
            commission: 0,
            administrationFeeValue: 1000,
            hasGratification: true,
            joinedTelemedicine: true,
            bank: 'Itaú',
            publicAgency: 'MiSupremo Tribunal Federal',
            contractModel: '',
            installmentNumber: 8,
            initialDate: '2022-11-05T00:00:00.000Z',
            financialAssistanceValue: 3648,
            installmentValue: 456,
            name: 'Márcio',
            lastName: 'Das Neves',
            gender: 'Masculino',
            birthDate: '1991-06-06T00:00:00.000Z',
            maritalStatus: 'Casado',
            nationality: 'Brasileiro',
            placeOfBirth: 'Poti',
            taxId: '884.747.923-12',
            registerId: '21.860.204-2',
            emissionState: 'Ceará',
            issuingAgency: 'Secretaria de Segurança Pública',
            emissionDate: '2022-10-10T00:00:00.000Z',
            cellPhone: '(88) 3768-4973',
            email: 'marcio.davi.dasneves@likaleal.com.br',
            father: 'Vicente Alexandre das Neves',
            mother: 'Allana Rafaela',
            partner: 'Joana Maria das Neves',
            occupation: 'Arquiteta',
            salary: '4312.20',
            paymentDay: 5,
            registerNumber: '2108602049',
            contractType: 'N',
            finalDate: null,
            agency: '000',
            accountType: 'Corrente',
            accountNumber: '23132',
            pixKey: 'eloa_freitas@superigi.com.br',
            pixType: null,
            addressType: 'HOUSE',
            postalCode: '78595-970',
            street: 'Avenida Governador Dante Martins de Oliveira 115',
            houseNumber: '123',
            complement: '',
            district: 'Centro',
            city: 'Apiacás',
            state: 'Mato Grosso',
            consultantId: null,
            type: 'N',
            status: 'UNDER_ANALYSIS',
            affiliationId: 1,
            createdBy: 'afonsobr',
            updatedBy: null,
            createdAt: '2022-10-05T02:01:33.000Z',
            updatedAt: '2022-10-11T00:40:08.829Z',
            deletedAt: null,
            affiliation: {
              id: 1,
              name: 'ASES Vitória',
              createdAt: '2022-10-05T02:01:32.000Z',
              updatedAt: '2022-10-12T21:58:04.970Z',
              deletedAt: null,
            },
            consultant: null,
          },
          {
            id: 3,
            associatedId: 1,
            commission: 0,
            administrationFeeValue: 1000,
            hasGratification: true,
            joinedTelemedicine: true,
            bank: 'Itaú',
            publicAgency: 'MiSupremo Tribunal Federal',
            contractModel: '',
            installmentNumber: 8,
            initialDate: '2022-11-05T00:00:00.000Z',
            financialAssistanceValue: 3648,
            installmentValue: 456,
            name: 'Márcio',
            lastName: 'Das Neves',
            gender: 'Masculino',
            birthDate: '1991-06-06T00:00:00.000Z',
            maritalStatus: 'Casado',
            nationality: 'Brasileiro',
            placeOfBirth: 'Poti',
            taxId: '884.747.923-12',
            registerId: '21.860.204-2',
            emissionState: 'Ceará',
            issuingAgency: 'Secretaria de Segurança Pública',
            emissionDate: '2022-10-10T00:00:00.000Z',
            cellPhone: '(88) 3768-4973',
            email: 'marcio.davi.dasneves@likaleal.com.br',
            father: 'Vicente Alexandre das Neves',
            mother: 'Allana Rafaela',
            partner: 'Joana Maria das Neves',
            occupation: 'Arquiteta',
            salary: '4312.20',
            paymentDay: 5,
            registerNumber: '2108602049',
            contractType: 'N',
            finalDate: null,
            agency: '000',
            accountType: 'Corrente',
            accountNumber: '23132',
            pixKey: 'eloa_freitas@superigi.com.br',
            pixType: null,
            addressType: 'HOUSE',
            postalCode: '78595-970',
            street: 'Avenida Governador Dante Martins de Oliveira 115',
            houseNumber: '123',
            complement: '',
            district: 'Centro',
            city: 'Apiacás',
            state: 'Mato Grosso',
            consultantId: null,
            type: 'N',
            status: 'UNDER_ANALYSIS',
            affiliationId: 1,
            createdBy: 'afonsobr',
            updatedBy: null,
            createdAt: '2022-10-05T02:01:33.000Z',
            updatedAt: '2022-10-11T00:42:21.210Z',
            deletedAt: null,
            affiliation: {
              id: 1,
              name: 'ASES Vitória',
              createdAt: '2022-10-05T02:01:32.000Z',
              updatedAt: '2022-10-12T21:58:04.970Z',
              deletedAt: null,
            },
            consultant: null,
          },
          {
            id: 4,
            associatedId: 1,
            commission: 0,
            administrationFeeValue: 1000,
            hasGratification: true,
            joinedTelemedicine: true,
            bank: 'Itaú',
            publicAgency: 'MiSupremo Tribunal Federal',
            contractModel: '',
            installmentNumber: 8,
            initialDate: '2022-11-05T00:00:00.000Z',
            financialAssistanceValue: 2898,
            installmentValue: 362.25,
            name: 'Márcio',
            lastName: 'Das Neves',
            gender: 'Masculino',
            birthDate: '1991-06-06T00:00:00.000Z',
            maritalStatus: 'Casado',
            nationality: 'Brasileiro',
            placeOfBirth: 'Poti',
            taxId: '884.747.923-12',
            registerId: '21.860.204-2',
            emissionState: 'Ceará',
            issuingAgency: 'Secretaria de Segurança Pública',
            emissionDate: '2022-10-10T00:00:00.000Z',
            cellPhone: '(88) 3768-4973',
            email: 'marcio.davi.dasneves@likaleal.com.br',
            father: 'Vicente Alexandre das Neves',
            mother: 'Allana Rafaela',
            partner: 'Joana Maria das Neves',
            occupation: 'Arquiteta',
            salary: '4312.20',
            paymentDay: 5,
            registerNumber: '2108602049',
            contractType: 'N',
            finalDate: null,
            agency: '000',
            accountType: 'Corrente',
            accountNumber: '23132',
            pixKey: 'eloa_freitas@superigi.com.br',
            pixType: null,
            addressType: 'HOUSE',
            postalCode: '78595-970',
            street: 'Avenida Governador Dante Martins de Oliveira 115',
            houseNumber: '123',
            complement: '',
            district: 'Centro',
            city: 'Apiacás',
            state: 'Mato Grosso',
            consultantId: null,
            type: 'N',
            status: 'UNDER_ANALYSIS',
            affiliationId: 1,
            createdBy: 'afonsobr',
            updatedBy: null,
            createdAt: '2022-10-05T02:01:33.000Z',
            updatedAt: '2022-10-11T00:47:21.855Z',
            deletedAt: null,
            affiliation: {
              id: 1,
              name: 'ASES Vitória',
              createdAt: '2022-10-05T02:01:32.000Z',
              updatedAt: '2022-10-12T21:58:04.970Z',
              deletedAt: null,
            },
            consultant: null,
          },
        ],
        affiliations: [
          {
            id: 1,
            name: 'ASES Vitória',
            createdAt: '2022-10-05T02:01:32.000Z',
            updatedAt: '2022-10-12T21:58:04.970Z',
            deletedAt: null,
          },
        ],
      },
    },
  },
} as { [key: string]: ExampleObject | ReferenceObject };
