import { ExampleObject, ReferenceObject } from 'openapi-comment-parser';

export default {
  GetAllBenefitsResponse: {
    value: {
      statusCode: 200,
      statusCodeAsString: 'OK',
      data: {
        totalResults: 4,
        totalPages: 1,
        currentPage: 1,
        data: [
          {
            id: 1,
            associatedId: 1,
            commission: 0,
            administrationFeeValue: 1000,
            hasGratification: true,
            joinedTelemedicine: true,
            bank: 'Itaú',
            publicAgency: 'MiSupremo Tribunal Federal',
            contractModel: '',
            installmentNumber: 8,
            initialDate: '2022-11-05T00:00:00.000Z',
            financialAssistanceValue: 3648,
            installmentValue: 456,
            name: 'Márcio',
            lastName: 'Das Neves',
            gender: 'Masculino',
            birthDate: '1991-06-06T00:00:00.000Z',
            maritalStatus: 'Casado',
            nationality: 'Brasileiro',
            placeOfBirth: 'Poti',
            taxId: '884.747.923-12',
            registerId: '21.860.204-2',
            emissionState: 'Ceará',
            issuingAgency: 'Secretaria de Segurança Pública',
            emissionDate: '2022-10-10T00:00:00.000Z',
            cellPhone: '(88) 3768-4973',
            email: 'marcio.davi.dasneves@likaleal.com.br',
            father: 'Vicente Alexandre das Neves',
            mother: 'Allana Rafaela',
            partner: 'Joana Maria das Neves',
            occupation: 'Arquiteta',
            salary: '4312.20',
            paymentDay: 5,
            registerNumber: '2108602049',
            contractType: 'N',
            finalDate: null,
            agency: '000',
            accountType: 'Corrente',
            accountNumber: '23132',
            pixKey: 'eloa_freitas@superigi.com.br',
            pixType: null,
            addressType: 'HOUSE',
            postalCode: '78595-970',
            street: 'Avenida Governador Dante Martins de Oliveira 115',
            houseNumber: '123',
            complement: '',
            district: 'Centro',
            city: 'Apiacás',
            state: 'Mato Grosso',
            consultantId: null,
            type: 'N',
            status: 'UNDER_ANALYSIS',
            affiliationId: 1,
            createdBy: 'João',
            updatedBy: null,
            createdAt: '2022-10-05T02:01:33.000Z',
            updatedAt: '2022-10-11T00:25:28.889Z',
            deletedAt: null,
            affiliation: {
              id: 1,
              name: 'ASES Vitória',
              createdAt: '2022-10-05T02:01:32.000Z',
              updatedAt: '2022-10-12T16:21:44.279Z',
              deletedAt: null,
            },
            associated: {
              id: 1,
              name: 'Márcio',
              lastName: 'Das Neves',
              gender: 'Masculino',
              birthDate: '1991-06-06T00:00:00.000Z',
              maritalStatus: 'Casado',
              nationality: 'Brasileiro',
              placeOfBirth: 'Poti',
              taxId: '884.747.923-12',
              registerId: '21.860.204-2',
              emissionState: 'Ceará',
              issuingAgency: 'Secretaria de Segurança Pública',
              emissionDate: '2022-10-10T00:00:00.000Z',
              cellPhone: '(88) 3768-4973',
              email: 'marcio.davi.dasneves@likaleal.com.br',
              father: 'Vicente Alexandre das Neves',
              mother: 'Allana Rafaela',
              partner: 'Joana Maria das Neves',
              createdBy: 'João',
              updatedBy: null,
              createdAt: '2022-10-05T02:01:33.000Z',
              updatedAt: '2022-10-12T16:21:44.769Z',
              deletedAt: null,
            },
            consultant: null,
          },
          {
            id: 2,
            associatedId: 1,
            commission: 0,
            administrationFeeValue: 1000,
            hasGratification: true,
            joinedTelemedicine: true,
            bank: 'Itaú',
            publicAgency: 'MiSupremo Tribunal Federal',
            contractModel: '',
            installmentNumber: 8,
            initialDate: '2022-11-05T00:00:00.000Z',
            financialAssistanceValue: 3648,
            installmentValue: 456,
            name: 'Márcio',
            lastName: 'Das Neves',
            gender: 'Masculino',
            birthDate: '1991-06-06T00:00:00.000Z',
            maritalStatus: 'Casado',
            nationality: 'Brasileiro',
            placeOfBirth: 'Poti',
            taxId: '884.747.923-12',
            registerId: '21.860.204-2',
            emissionState: 'Ceará',
            issuingAgency: 'Secretaria de Segurança Pública',
            emissionDate: '2022-10-10T00:00:00.000Z',
            cellPhone: '(88) 3768-4973',
            email: 'marcio.davi.dasneves@likaleal.com.br',
            father: 'Vicente Alexandre das Neves',
            mother: 'Allana Rafaela',
            partner: 'Joana Maria das Neves',
            occupation: 'Arquiteta',
            salary: '4312.20',
            paymentDay: 5,
            registerNumber: '2108602049',
            contractType: 'N',
            finalDate: null,
            agency: '000',
            accountType: 'Corrente',
            accountNumber: '23132',
            pixKey: 'eloa_freitas@superigi.com.br',
            pixType: null,
            addressType: 'HOUSE',
            postalCode: '78595-970',
            street: 'Avenida Governador Dante Martins de Oliveira 115',
            houseNumber: '123',
            complement: '',
            district: 'Centro',
            city: 'Apiacás',
            state: 'Mato Grosso',
            consultantId: null,
            type: 'N',
            status: 'UNDER_ANALYSIS',
            affiliationId: 1,
            createdBy: 'afonsobr',
            updatedBy: null,
            createdAt: '2022-10-05T02:01:33.000Z',
            updatedAt: '2022-10-11T00:40:08.829Z',
            deletedAt: null,
            affiliation: {
              id: 1,
              name: 'ASES Vitória',
              createdAt: '2022-10-05T02:01:32.000Z',
              updatedAt: '2022-10-12T16:21:44.279Z',
              deletedAt: null,
            },
            associated: {
              id: 1,
              name: 'Márcio',
              lastName: 'Das Neves',
              gender: 'Masculino',
              birthDate: '1991-06-06T00:00:00.000Z',
              maritalStatus: 'Casado',
              nationality: 'Brasileiro',
              placeOfBirth: 'Poti',
              taxId: '884.747.923-12',
              registerId: '21.860.204-2',
              emissionState: 'Ceará',
              issuingAgency: 'Secretaria de Segurança Pública',
              emissionDate: '2022-10-10T00:00:00.000Z',
              cellPhone: '(88) 3768-4973',
              email: 'marcio.davi.dasneves@likaleal.com.br',
              father: 'Vicente Alexandre das Neves',
              mother: 'Allana Rafaela',
              partner: 'Joana Maria das Neves',
              createdBy: 'João',
              updatedBy: null,
              createdAt: '2022-10-05T02:01:33.000Z',
              updatedAt: '2022-10-12T16:21:44.769Z',
              deletedAt: null,
            },
            consultant: null,
          },
          {
            id: 3,
            associatedId: 1,
            commission: 0,
            administrationFeeValue: 1000,
            hasGratification: true,
            joinedTelemedicine: true,
            bank: 'Itaú',
            publicAgency: 'MiSupremo Tribunal Federal',
            contractModel: '',
            installmentNumber: 8,
            initialDate: '2022-11-05T00:00:00.000Z',
            financialAssistanceValue: 3648,
            installmentValue: 456,
            name: 'Márcio',
            lastName: 'Das Neves',
            gender: 'Masculino',
            birthDate: '1991-06-06T00:00:00.000Z',
            maritalStatus: 'Casado',
            nationality: 'Brasileiro',
            placeOfBirth: 'Poti',
            taxId: '884.747.923-12',
            registerId: '21.860.204-2',
            emissionState: 'Ceará',
            issuingAgency: 'Secretaria de Segurança Pública',
            emissionDate: '2022-10-10T00:00:00.000Z',
            cellPhone: '(88) 3768-4973',
            email: 'marcio.davi.dasneves@likaleal.com.br',
            father: 'Vicente Alexandre das Neves',
            mother: 'Allana Rafaela',
            partner: 'Joana Maria das Neves',
            occupation: 'Arquiteta',
            salary: '4312.20',
            paymentDay: 5,
            registerNumber: '2108602049',
            contractType: 'N',
            finalDate: null,
            agency: '000',
            accountType: 'Corrente',
            accountNumber: '23132',
            pixKey: 'eloa_freitas@superigi.com.br',
            pixType: null,
            addressType: 'HOUSE',
            postalCode: '78595-970',
            street: 'Avenida Governador Dante Martins de Oliveira 115',
            houseNumber: '123',
            complement: '',
            district: 'Centro',
            city: 'Apiacás',
            state: 'Mato Grosso',
            consultantId: null,
            type: 'N',
            status: 'UNDER_ANALYSIS',
            affiliationId: 1,
            createdBy: 'afonsobr',
            updatedBy: null,
            createdAt: '2022-10-05T02:01:33.000Z',
            updatedAt: '2022-10-11T00:42:21.210Z',
            deletedAt: null,
            affiliation: {
              id: 1,
              name: 'ASES Vitória',
              createdAt: '2022-10-05T02:01:32.000Z',
              updatedAt: '2022-10-12T16:21:44.279Z',
              deletedAt: null,
            },
            associated: {
              id: 1,
              name: 'Márcio',
              lastName: 'Das Neves',
              gender: 'Masculino',
              birthDate: '1991-06-06T00:00:00.000Z',
              maritalStatus: 'Casado',
              nationality: 'Brasileiro',
              placeOfBirth: 'Poti',
              taxId: '884.747.923-12',
              registerId: '21.860.204-2',
              emissionState: 'Ceará',
              issuingAgency: 'Secretaria de Segurança Pública',
              emissionDate: '2022-10-10T00:00:00.000Z',
              cellPhone: '(88) 3768-4973',
              email: 'marcio.davi.dasneves@likaleal.com.br',
              father: 'Vicente Alexandre das Neves',
              mother: 'Allana Rafaela',
              partner: 'Joana Maria das Neves',
              createdBy: 'João',
              updatedBy: null,
              createdAt: '2022-10-05T02:01:33.000Z',
              updatedAt: '2022-10-12T16:21:44.769Z',
              deletedAt: null,
            },
            consultant: null,
          },
          {
            id: 4,
            associatedId: 1,
            commission: 0,
            administrationFeeValue: 1000,
            hasGratification: true,
            joinedTelemedicine: true,
            bank: 'Itaú',
            publicAgency: 'MiSupremo Tribunal Federal',
            contractModel: '',
            installmentNumber: 8,
            initialDate: '2022-11-05T00:00:00.000Z',
            financialAssistanceValue: 2898,
            installmentValue: 362.25,
            name: 'Márcio',
            lastName: 'Das Neves',
            gender: 'Masculino',
            birthDate: '1991-06-06T00:00:00.000Z',
            maritalStatus: 'Casado',
            nationality: 'Brasileiro',
            placeOfBirth: 'Poti',
            taxId: '884.747.923-12',
            registerId: '21.860.204-2',
            emissionState: 'Ceará',
            issuingAgency: 'Secretaria de Segurança Pública',
            emissionDate: '2022-10-10T00:00:00.000Z',
            cellPhone: '(88) 3768-4973',
            email: 'marcio.davi.dasneves@likaleal.com.br',
            father: 'Vicente Alexandre das Neves',
            mother: 'Allana Rafaela',
            partner: 'Joana Maria das Neves',
            occupation: 'Arquiteta',
            salary: '4312.20',
            paymentDay: 5,
            registerNumber: '2108602049',
            contractType: 'N',
            finalDate: null,
            agency: '000',
            accountType: 'Corrente',
            accountNumber: '23132',
            pixKey: 'eloa_freitas@superigi.com.br',
            pixType: null,
            addressType: 'HOUSE',
            postalCode: '78595-970',
            street: 'Avenida Governador Dante Martins de Oliveira 115',
            houseNumber: '123',
            complement: '',
            district: 'Centro',
            city: 'Apiacás',
            state: 'Mato Grosso',
            consultantId: null,
            type: 'N',
            status: 'UNDER_ANALYSIS',
            affiliationId: 1,
            createdBy: 'afonsobr',
            updatedBy: null,
            createdAt: '2022-10-05T02:01:33.000Z',
            updatedAt: '2022-10-11T00:47:21.855Z',
            deletedAt: null,
            affiliation: {
              id: 1,
              name: 'ASES Vitória',
              createdAt: '2022-10-05T02:01:32.000Z',
              updatedAt: '2022-10-12T16:21:44.279Z',
              deletedAt: null,
            },
            associated: {
              id: 1,
              name: 'Márcio',
              lastName: 'Das Neves',
              gender: 'Masculino',
              birthDate: '1991-06-06T00:00:00.000Z',
              maritalStatus: 'Casado',
              nationality: 'Brasileiro',
              placeOfBirth: 'Poti',
              taxId: '884.747.923-12',
              registerId: '21.860.204-2',
              emissionState: 'Ceará',
              issuingAgency: 'Secretaria de Segurança Pública',
              emissionDate: '2022-10-10T00:00:00.000Z',
              cellPhone: '(88) 3768-4973',
              email: 'marcio.davi.dasneves@likaleal.com.br',
              father: 'Vicente Alexandre das Neves',
              mother: 'Allana Rafaela',
              partner: 'Joana Maria das Neves',
              createdBy: 'João',
              updatedBy: null,
              createdAt: '2022-10-05T02:01:33.000Z',
              updatedAt: '2022-10-12T16:21:44.769Z',
              deletedAt: null,
            },
            consultant: null,
          },
        ],
      },
    },
  },
  GetBenefitByIdResponse: {
    value: {
      statusCode: 200,
      statusCodeAsString: 'OK',
      data: {
        id: 1,
        associatedId: 1,
        commission: 0,
        administrationFeeValue: 1000,
        hasGratification: true,
        joinedTelemedicine: true,
        bank: 'Itaú',
        publicAgency: 'MiSupremo Tribunal Federal',
        contractModel: '',
        installmentNumber: 8,
        initialDate: '2022-11-05T00:00:00.000Z',
        financialAssistanceValue: 3648,
        installmentValue: 456,
        name: 'Márcio',
        lastName: 'Das Neves',
        gender: 'Masculino',
        birthDate: '1991-06-06T00:00:00.000Z',
        maritalStatus: 'Casado',
        nationality: 'Brasileiro',
        placeOfBirth: 'Poti',
        taxId: '884.747.923-12',
        registerId: '21.860.204-2',
        emissionState: 'Ceará',
        issuingAgency: 'Secretaria de Segurança Pública',
        emissionDate: '2022-10-10T00:00:00.000Z',
        cellPhone: '(88) 3768-4973',
        email: 'marcio.davi.dasneves@likaleal.com.br',
        father: 'Vicente Alexandre das Neves',
        mother: 'Allana Rafaela',
        partner: 'Joana Maria das Neves',
        occupation: 'Arquiteta',
        salary: '4312.20',
        paymentDay: 5,
        registerNumber: '2108602049',
        contractType: 'N',
        finalDate: null,
        agency: '000',
        accountType: 'Corrente',
        accountNumber: '23132',
        pixKey: 'eloa_freitas@superigi.com.br',
        pixType: null,
        addressType: 'HOUSE',
        postalCode: '78595-970',
        street: 'Avenida Governador Dante Martins de Oliveira 115',
        houseNumber: '123',
        complement: '',
        district: 'Centro',
        city: 'Apiacás',
        state: 'Mato Grosso',
        consultantId: null,
        type: 'N',
        status: 'UNDER_ANALYSIS',
        affiliationId: 1,
        createdBy: 'João',
        updatedBy: null,
        createdAt: '2022-10-05T02:01:33.000Z',
        updatedAt: '2022-10-11T00:25:28.889Z',
        deletedAt: null,
        affiliation: {
          id: 1,
          name: 'ASES Vitória',
          createdAt: '2022-10-05T02:01:32.000Z',
          updatedAt: '2022-10-12T16:21:44.279Z',
          deletedAt: null,
        },
        associated: {
          id: 1,
          name: 'Márcio',
          lastName: 'Das Neves',
          gender: 'Masculino',
          birthDate: '1991-06-06T00:00:00.000Z',
          maritalStatus: 'Casado',
          nationality: 'Brasileiro',
          placeOfBirth: 'Poti',
          taxId: '884.747.923-12',
          registerId: '21.860.204-2',
          emissionState: 'Ceará',
          issuingAgency: 'Secretaria de Segurança Pública',
          emissionDate: '2022-10-10T00:00:00.000Z',
          cellPhone: '(88) 3768-4973',
          email: 'marcio.davi.dasneves@likaleal.com.br',
          father: 'Vicente Alexandre das Neves',
          mother: 'Allana Rafaela',
          partner: 'Joana Maria das Neves',
          createdBy: 'João',
          updatedBy: null,
          createdAt: '2022-10-05T02:01:33.000Z',
          updatedAt: '2022-10-12T16:21:44.769Z',
          deletedAt: null,
        },
        consultant: null,
      },
    },
  },
} as { [key: string]: ExampleObject | ReferenceObject };
