openapi: 3.0.1
info:
  version: 1.0.0
  title: haand-bib Web Service
  description: haand-bib is webservice to provide features to haand-bib.
  contact:
    email: brunohafonso@gmail.com
servers:
  - url: http://localhost:3000/
    description: Local server
tags:
  - name: Healthcheck
    description: Healthcheck endpoints that contains all the operations of the healthcheck
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: x-access-token
      in: header
  examples:
    HealthlyResponse:
      value:
        statusCode: 200
        statusCodeAsString: OK
        data:
          name: haand-bid
          version: 1.0.0
          uptime: 948 secs
          status: healthly
          database:
            status: healthly
            connectionStatus: connected
    UnhealthlyResponse:
      value:
        statusCode: 500
        statusCodeAsString: INTERNAL_SERVER_ERROR
        data:
          name: haand-bid
          version: 1.0.0
          uptime: 1225 secs
          status: unhealthy
          database:
            status: unhealthy
            connectionStatus: disconnected
    CreateConsultantResponse:
      type: object
      properties:
        name:
          type: string
          example: String
        taxId:
          type: string
          example: 01020312465
        city:
          type: string
          example: São Luis
        state:
          type: string
          example: Maranhão
        commission:
          type: integer
          format: int32
          example: 10
        createdBy:
          type: string
          example: admin
        updatedBy:
          type: string
          example: admin
        createdAt:
          type: string
          example: 10-10-2020
        updatedAt:
          type: string
          example: 20-03-2021
        deletedAt:
          type: string
          example: 03-09-2022
    ConsultantsResponse:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            example: John Doe
          taxId:
            type: string
            example: 01020312465
          city:
            type: string
            example: São Luis
          state:
            type: string
            example: Maranhão
          commission:
            type: integer
            format: int32
            example: 10
    ConsultantResponse:
      type: object
      properties:
        name:
          type: string
          example: String
        taxId:
          type: string
          example: 01020312465
        city:
          type: string
          example: São Luis
        state:
          type: string
          example: Maranhão
        commission:
          type: integer
          format: int32
          example: 10
        createdBy:
          type: string
          example: admin
        updatedBy:
          type: string
          example: admin
        createdAt:
          type: string
          example: 10-10-2020
        updatedAt:
          type: string
          example: 20-03-2021
        deletedAt:
          type: string
          example: 03-09-2022
  schemas:
    ConsultantsResponse:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            example: John Doe
          taxId:
            type: string
            example: 01020312465
          city:
            type: string
            example: São Luis
          state:
            type: string
            example: Maranhão
          commission:
            type: integer
            format: int32
            example: 10
    CreateConsultantPayload:
      type: object
      properties:
        name:
          type: string
          example: Jane Doe
        taxId:
          type: string
          example: 01020312465
        city:
          type: string
          example: São Luis
        state:
          type: string
          example: Maranhão
        commission:
          type: integer
          format: int32
          example: 10
    UpdateConsultantPayload:
      type: object
      properties:
        name:
          type: string
          example: Jane Doe
        taxId:
          type: string
          example: 01020312465
        city:
          type: string
          example: São Luis
        state:
          type: string
          example: Maranhão
        commission:
          type: integer
          format: int32
          example: 10
    CreateConsultantResponse:
      type: object
      properties:
        name:
          type: string
          example: String
        taxId:
          type: string
          example: 01020312465
        city:
          type: string
          example: São Luis
        state:
          type: string
          example: Maranhão
        commission:
          type: integer
          format: int32
          example: 10
        createdBy:
          type: string
          example: admin
        updatedBy:
          type: string
          example: admin
        createdAt:
          type: string
          example: 10-10-2020
        updatedAt:
          type: string
          example: 20-03-2021
        deletedAt:
          type: string
          example: 03-09-2022
    UpdateConsultantResponse:
      type: object
      properties:
        message:
          type: string
          example: No Content
    ConsultantResponse:
      type: object
      properties:
        name:
          type: string
          example: String
        taxId:
          type: string
          example: 01020312465
        city:
          type: string
          example: São Luis
        state:
          type: string
          example: Maranhão
        commission:
          type: integer
          format: int32
          example: 10
        createdBy:
          type: string
          example: admin
        updatedBy:
          type: string
          example: admin
        createdAt:
          type: string
          example: 10-10-2020
        updatedAt:
          type: string
          example: 20-03-2021
        deletedAt:
          type: string
          example: 03-09-2022
    ConsultantBadRequestResponse:
      type: object
      properties:
        message:
          type: string
          example: Invalid Params
    HealthcheckResponse:
      type: object
      properties:
        statusCode:
          type: number
          description: http status code
        statusCodeAsString:
          type: string
          description: http status code as string
        data:
          type: object
          description: an object with the response
          properties:
            name:
              type: string
            version:
              type: string
              description: application version
            uptime:
              type: string
              description: time that the application is running
            status:
              type: string
              description: status of the application
              enum:
                - healthly
                - unhealthy
            database:
              type: object
              properties:
                status:
                  type: string
                  description: status of the database
                  enum:
                    - healthly
                    - unhealthy
                connectionStatus:
                  type: string
                  description: status of the database connection
                  enum:
                    - connected
                    - disconnected
    InternalServerErrorResponse:
      type: object
      properties:
        code:
          type: string
          example: GENERIC_ERROR
        statusCode:
          type: number
          example: 500
        statusCodeAsString:
          type: string
          example: INTERNAL_SERVER_ERROR
        description:
          type: string
          example: Internal Server Error
    BadRequestResponse:
      type: object
      properties:
        code:
          type: string
          example: GENERIC_ERROR
        statusCode:
          type: number
          example: 400
        statusCodeAsString:
          type: string
          example: BAD_REQUEST
        description:
          type: string
          example: Missing or invalid param
        validationErrors:
          type: array
          items:
            properties:
              field:
                type: string
                example: name
              message:
                type: string
                example: name is required
    NotFoundResponse:
      type: object
      properties:
        code:
          type: string
          example: GENERIC_ERROR
        statusCode:
          type: number
          example: 404
        statusCodeAsString:
          type: string
          example: NOT_FOUND
        description:
          type: string
          example: Resource not found
    UnauthorizedResponse:
      type: object
      properties:
        code:
          type: string
          example: GENERIC_ERROR
        statusCode:
          type: number
          example: 401
        statusCodeAsString:
          type: string
          example: UNAUTHORIZED
        description:
          type: string
          example: token not provided
    TooManyRequestsResponse:
      type: object
      properties:
        code:
          type: string
          example: GENERIC_ERROR
        statusCode:
          type: number
          example: 429
        statusCodeAsString:
          type: string
          example: TOO_MANY_REQUESTS
        description:
          type: string
          example: you reach the limit of requests for this resource
    ForbiddenResponse:
      type: object
      properties:
        code:
          type: string
          example: GENERIC_ERROR
        statusCode:
          type: number
          example: 403
        statusCodeAsString:
          type: string
          example: FORBIDDEN
        description:
          type: string
          example: you dont have permission to access this resource
